import globals from "globals"
import pluginJs from "@eslint/js"
import pluginVue from "eslint-plugin-vue"

/** @type {import('eslint').Linter.Config[]} */
export default [
  { files: ["**/*.{js,mjs,cjs,vue}"] },
  { languageOptions: { globals: globals.browser } },
  pluginJs.configs.recommended,
  ...pluginVue.configs["flat/essential"],
  {
    rules: {
      "no-unused-vars": "error",
      "getter-return": "error",
      "no-cond-assign": "error",
      "no-constant-condition": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-extra-semi": "error",
      "no-inner-declarations": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "use-isnan": "error",
      "block-scoped-var": "error",
      "curly": ["error", "all"],
      "no-extend-native": "error",
      "no-global-assign": "error",
      "no-implicit-globals": "error",
      "no-invalid-this": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-octal": "error",
      "no-octal-escape": "error",
      "no-proto": "error",
      "no-redeclare": "error",
      "no-return-assign": "error",
      "no-unused-expressions": "error",
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "no-useless-escape": "error",
      "no-useless-return": "error",
      "require-await": "error",
      "vars-on-top": "error",
      "no-catch-shadow": "error",
      "no-shadow": "error",
      "no-shadow-restricted-names": "error",
      "no-undef": "error",
      "array-bracket-spacing": ["error", "never"],
      "block-spacing": ["error", "always"],
      "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
      "comma-spacing": ["error", { "before": false, "after": true }],
      "func-call-spacing": ["error", "never"],
      "indent": ["error", 2],
      "linebreak-style": ["error", "unix"],
      "new-parens": "error",
      "no-lonely-if": "error",
      "no-mixed-spaces-and-tabs": "error",
      "no-tabs": "error",
      "no-trailing-spaces": "error",
      "object-curly-spacing": ["error", "always"],
      "one-var-declaration-per-line": ["error", "initializations"],
      "semi": ["error", "never"],
      "space-before-blocks": ["error", "always"],
      "space-before-function-paren": ["error", "always"],
      "space-in-parens": ["error", "never"],
      "space-infix-ops": ["error", { "int32Hint": false }],
      "space-unary-ops": ["error", { "words": true, "nonwords": false }],
      "switch-colon-spacing": ["error", { "after": true, "before": false }],
      "arrow-parens": ["error", "as-needed"],
      "no-confusing-arrow": "error",
      "no-const-assign": "error",
      "no-dupe-class-members": "error",
      "no-duplicate-imports": "error",
      "no-var": "error"
    }
  }
]
